// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserID struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserID) Reset()         { *m = UserID{} }
func (m *UserID) String() string { return proto.CompactTextString(m) }
func (*UserID) ProtoMessage()    {}
func (*UserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserID.Unmarshal(m, b)
}
func (m *UserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserID.Marshal(b, m, deterministic)
}
func (m *UserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserID.Merge(m, src)
}
func (m *UserID) XXX_Size() int {
	return xxx_messageInfo_UserID.Size(m)
}
func (m *UserID) XXX_DiscardUnknown() {
	xxx_messageInfo_UserID.DiscardUnknown(m)
}

var xxx_messageInfo_UserID proto.InternalMessageInfo

func (m *UserID) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type EmptyArgs struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyArgs) Reset()         { *m = EmptyArgs{} }
func (m *EmptyArgs) String() string { return proto.CompactTextString(m) }
func (*EmptyArgs) ProtoMessage()    {}
func (*EmptyArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *EmptyArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyArgs.Unmarshal(m, b)
}
func (m *EmptyArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyArgs.Marshal(b, m, deterministic)
}
func (m *EmptyArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyArgs.Merge(m, src)
}
func (m *EmptyArgs) XXX_Size() int {
	return xxx_messageInfo_EmptyArgs.Size(m)
}
func (m *EmptyArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyArgs.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyArgs proto.InternalMessageInfo

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type User struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	SecondName           string   `protobuf:"bytes,4,opt,name=SecondName,proto3" json:"SecondName,omitempty"`
	UserName             string   `protobuf:"bytes,5,opt,name=UserName,proto3" json:"UserName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetSecondName() string {
	if m != nil {
		return m.SecondName
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func init() {
	proto.RegisterType((*UserID)(nil), "support.UserID")
	proto.RegisterType((*EmptyArgs)(nil), "support.EmptyArgs")
	proto.RegisterType((*Users)(nil), "support.Users")
	proto.RegisterType((*User)(nil), "support.User")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0xd7, 0xfd, 0xdf, 0x1d, 0x4e, 0xb8, 0xf8, 0x50, 0x8a, 0x48, 0x89, 0x0f, 0x56, 0x98,
	0x2d, 0xcc, 0x4f, 0xb0, 0xd1, 0x0d, 0xfa, 0xe2, 0x43, 0x87, 0x2f, 0xbe, 0x6d, 0x6d, 0xac, 0xd5,
	0xb6, 0x09, 0x49, 0x2a, 0xee, 0x0b, 0xf8, 0xb9, 0x25, 0x59, 0xa9, 0xd6, 0xa7, 0x9c, 0x7b, 0x7e,
	0x87, 0x9b, 0xe4, 0x00, 0xd4, 0x92, 0x0a, 0x9f, 0x0b, 0xa6, 0x18, 0x4e, 0x64, 0xcd, 0x39, 0x13,
	0x8a, 0xd8, 0x30, 0x7e, 0x96, 0x54, 0x44, 0x21, 0x2e, 0xa0, 0x1f, 0x85, 0xb6, 0xe5, 0x5a, 0xde,
	0x20, 0xee, 0x47, 0x21, 0x99, 0xc3, 0x6c, 0x5b, 0x72, 0x75, 0x5a, 0x8b, 0x4c, 0x92, 0x25, 0x8c,
	0x74, 0x4c, 0xe2, 0x6d, 0x23, 0x6c, 0xcb, 0x1d, 0x78, 0xf3, 0xd5, 0x85, 0xdf, 0x2c, 0xf2, 0xb5,
	0x1b, 0x9f, 0x19, 0xf9, 0xb6, 0x60, 0xa8, 0xd5, 0xff, 0x9d, 0x78, 0x05, 0xa3, 0x6d, 0x79, 0xc8,
	0x0b, 0xbb, 0xef, 0x5a, 0xde, 0x2c, 0x3e, 0x0f, 0x78, 0x0d, 0xb3, 0x5d, 0x2e, 0xa4, 0x7a, 0x3a,
	0x94, 0xd4, 0x1e, 0x18, 0xf2, 0x6b, 0xe0, 0x0d, 0xc0, 0x9e, 0x26, 0xac, 0x4a, 0x0d, 0x1e, 0x1a,
	0xfc, 0xc7, 0x41, 0x07, 0xa6, 0xfa, 0x2e, 0x43, 0x47, 0x86, 0xb6, 0xf3, 0xaa, 0x80, 0xb9, 0xd6,
	0x7b, 0x2a, 0x3e, 0xf3, 0x84, 0xe2, 0x12, 0xa6, 0xbb, 0xbc, 0x4a, 0x37, 0xa7, 0x28, 0xc5, 0xcb,
	0xce, 0xcb, 0xa3, 0xd0, 0xe9, 0x7e, 0x85, 0xf4, 0x30, 0x80, 0x89, 0x4e, 0xaf, 0x8b, 0x02, 0xb1,
	0x65, 0x6d, 0x25, 0xce, 0xa2, 0x93, 0x97, 0xa4, 0xb7, 0xb9, 0x7f, 0xb9, 0xcb, 0x72, 0xf5, 0x56,
	0x1f, 0xfd, 0x84, 0x95, 0x01, 0x67, 0xef, 0x95, 0x7a, 0xfd, 0x0a, 0x32, 0xf6, 0xd0, 0x04, 0x03,
	0xfe, 0x91, 0x05, 0xa6, 0xff, 0xe3, 0xd8, 0x1c, 0x8f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc5,
	0xee, 0xbf, 0x66, 0x94, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	FindById(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*User, error)
	FindAll(ctx context.Context, in *EmptyArgs, opts ...grpc.CallOption) (*Users, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) FindById(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/support.UserService/FindById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) FindAll(ctx context.Context, in *EmptyArgs, opts ...grpc.CallOption) (*Users, error) {
	out := new(Users)
	err := c.cc.Invoke(ctx, "/support.UserService/FindAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	FindById(context.Context, *UserID) (*User, error)
	FindAll(context.Context, *EmptyArgs) (*Users, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) FindById(ctx context.Context, req *UserID) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindById not implemented")
}
func (*UnimplementedUserServiceServer) FindAll(ctx context.Context, req *EmptyArgs) (*Users, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_FindById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).FindById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/support.UserService/FindById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).FindById(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/support.UserService/FindAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).FindAll(ctx, req.(*EmptyArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "support.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindById",
			Handler:    _UserService_FindById_Handler,
		},
		{
			MethodName: "FindAll",
			Handler:    _UserService_FindAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
